### ISSUE TITLE
committing-devs.gpg blindly trusted

### ISSUE THREAD

**Issue by crtxcr** [mgorny/gverify#1]
I was happy to see that blog post announcing this tool. Although not a gentoo dev,  this could still be useful for users . I have taken a quick  look at gvgit and discovered some potential issues:

The script assumes that https://qa-reports.gentoo.org/output/committing-devs.gpg has not been tampered with. What is the process that generates the keyring, or who does it? But that may not even be relevant, an attacker that compromises the infrastructure may also perhaps compromise that qa-reports server. People will run gverify, which will fetch the compromised commiting-devs.gpg (unless cache is still fresh enough, but that is just luck then) and all checks will pass.

The security also then completely relies on https and the certificate authority system, since no cert pinning is used. Furthermore, it assumes that the wget it uses from PATH will correclty handle https connection. While perhaps a fair assumption for GNU wget, this is not true for busybox wget, which does not check certificates. Currently however, (luckily) it wouldn't work with busybox wget anyway, since it doesn't have the -N option. Thus, perhaps the commting-devs.gpg should itself be signed, which then of course is only of value if it not an automated signing key.

I realize it's a "Trivial gentoo.git signature verification tool", but I'm afraid due to the issues mentioned above, at this time it may not be a sufficient way to protect users and devs against some more sophisticated attacks on infrastrucuture servers.

**Comment by mgorny** [comment]
The bundle is used merely to fetch keys. Authentication is done through gkeys seeds. However, this needs to change anyway as gkeys are dead.
